# This is a basic workflow to help you get started with Actions

name: 西梅

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/niubi-66/B.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【xim】'
        run: |
          cd ~/js   
          node Task/xim.js
